name: s
version: 0.1.1
github: thyeem/s
license: MIT
author: Francis Lim
maintainer: thyeem@gmail.com
copyright: 2022-2024 Francis
synopsis: parser combinators
category: parsing
description: |
  The parser-S is a generalized parser combinator easy-to-read.
  It is designed to focused on usability, scalability and non-verbosity.
  .

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base
- bytestring
- containers
- haskeline
- here
- pretty-simple
- text

ghc-options:
- -O2
- -Wall
- -Wno-name-shadowing
- -Wno-orphans

library:
  source-dirs: src

tests:
  doctest:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    dependencies:
    - base
    - Glob
    - doctest
    - s
