name: s
version: 0.1.1
github: thyeem/s
license: MIT
author: Francis Lim
maintainer: thyeem@gmail.com
copyright: 2022-2024 Francis
synopsis: parser combinators
category: parsing
description: |
  's' is a generalized parser combinator extremely easy to use.
  It is a frill-less design that focuses on the essence of parsing work
  .

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wno-orphans

library:
  source-dirs: src
  ghc-options:
  - -O2
  dependencies:
  - base
  - bytestring
  - containers
  - haskeline
  - pretty-simple
  - text

tests:
  doctest:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    dependencies:
    - base
    - Glob
    - doctest
    - s
