name: s
version: 0.1.1
github: thyeem/s
license: MIT
author: Francis Lim
maintainer: thyeem@gmail.com
copyright: 2022-2024 Francis
synopsis: parser combinators
category: parsing
description: |
  The parser-S is a generalized parser combinator easy-to-read.
  It is designed to focused on usability, scalability and non-verbosity.
  .

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base
- bytestring
- containers
- deepseq
- directory
- filepath
- haskeline
- parallel
- pretty-simple
- random
- raw-strings-qq
- text
- vector

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-orphans

library:
  source-dirs: src

executables:
  s-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -g0
    dependencies:
    - base
    - containers
    - directory
    - text
    - vector
    - s
    when:
    - condition: false
      other-modules: Paths_s

tests:
  doctest:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - base
    - Glob
    - doctest
    - s
