name:                s
version:             0.1.0.0
synopsis:            parser combinators
description: |
  The parser-S is a generalized parser combinator easy-to-read.
  It is designed to focused on usability, scalability and non-verbosity.
  .
category:            Parsing
author:              "Francis Lim <thyeem@gmail.com>"
copyright:           "Francis, 2022"
maintainer:          "Francis Lim <thyeem@gmail.com>"
license:             MIT

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - deepseq
  - parallel
  - random
  - raw-strings-qq
  - text
  - pretty-simple
  # - yaml
  # - aeson
  # - docopt >= 0.7.0.6

default-extensions:
  - StrictData
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - Trustworthy
  - TupleSections
  - TypeOperators
  - TypeSynonymInstances

library:
  source-dirs: src

executables:
  s:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -O0
      - -g0
      # - -threaded
      # - -rtsopts
      # - -with-rtsopts=-N
      # - -dynamic
      # - -feager-blackholing        -- useful for paralleism
    dependencies:
      - s
    when:
      - condition: false
        other-modules: Paths_s

tests:
  s-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - doctest
      - s
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2

benchmarks:
  bench:
    source-dirs: bench
    main: Benchmarks.hs
    dependencies:
      - criterion
      - parsec
      - attoparsec
      - megaparsec
      - flatparse
      - s
    ghc-options:
      - -O2
